apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-quality-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: air-quality-predictor
  template:
    metadata:
      labels:
        app: air-quality-predictor
    spec:
      containers:
      - name: air-quality-predictor
        image: air-quality-predictor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PREPROCESSOR_PATH
          value: "/app/data/processed/preprocessor.pkl"
        - name: MODEL_PATH
          value: "/app/models/final_model.pkl"
        - name: LABEL_ENCODER_PATH
          value: "/app/data/processed/label_encoder.pkl"
        resources: # Optional resource management
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
